name: CI/CD Pipeline Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l’image Docker
        run: docker build -t devops-app .

      - name: Build de l’image Docker
        run: docker build -t localhost:5000/devops-app:latest .

      - name: Pousser l’image vers le registre local
        run: docker push localhost:5000/devops-app:latest

      - name: Arrêter le conteneur en cours (si existe)
        continue-on-error: true
        run: docker stop devops-app || true

      - name: Supprimer l’ancien conteneur (si existe)
        continue-on-error: true
        run: docker rm devops-app || true

      - name: Lancer un nouveau conteneur avec l’image locale
        run: docker run -d --name devops-app -p 3000:3000 localhost:5000/devops:latest